### ISSUE TITLE
Brand is hard coded

### ISSUE THREAD

**Issue by dowlingw** [samgreenwood/swapshop#5]
The branding is hard coded as `Air-Stream`.
This should be configurable in the `application.php` or removed

**Comment by samgreenwood** [comment]
How do you feel about adding a swapshop.php configuration file, that way we can toggle things like branding. authentication providers etc in there.

**Comment by dowlingw** [comment]
Let's have a discussion about authentication in another ticket.

Re: branding - not really a php or laravel dev, though I've seen it done in asset names based on the application profile before.

Probably makes more sense to have them in the application config more than its own file tbh - but whatever you think works best.

**Comment by dowlingw** [comment]
Fixed in #8, closing
